services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - python_executor
      - cpp_executor
      - java_executor

  python_executor:
    build:
      context: ./backend/executors/python
      dockerfile: Dockerfile-python  
    ports:
      - "5001:5001"

  cpp_executor:
    build:
      context: ./backend/executors/cpp
      dockerfile: Dockerfile-cpp
    ports:
      - "5002:5002"

  java_executor:
    build:
      context: ./backend/executors/java
      dockerfile: Dockerfile-java
    ports:
      - "5003:5003"
