# Dockerfile-cpp
FROM gcc:latest
RUN apt-get update && apt-get install -y python3 python3-venv
WORKDIR /executor
COPY executor_cpp.py /executor/

# Créer et activer un environnement virtuel pour installer Flask
RUN python3 -m venv /executor/venv && \
    /executor/venv/bin/pip install flask

CMD ["/executor/venv/bin/python", "executor_cpp.py"]
